### ISSUE TITLE
"Response is not a function" Node Error: InitCrypto.js : Line 9

### ISSUE THREAD

**Issue by jadenmitchell** [HeyItsKawaii/Habbo#2]
<strong>Error Code:</strong>
<hr>var response = new Response(global.Outgoing.InitCryptoMessageComposer);

**Comment by boraida** [comment]
You are exporting an object with 1 property 'Response'. When you require it, the object will be:
{
    Response: function() { ... }
}

So that's why you should modify this:
var Response = require('../Response');

to:
var Response = require('../Response').Response;
